# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Archivebyarunavabasucom < Formula
  desc ""
  homepage "https://github.com/archivebyarunavabasucom/homebrewtaps"
  version "0.0.3"

  on_macos do
    url "https://github.com/archivebyarunavabasucom/publishgo/releases/download/0.0.3/publishgo_0.0.3_darwin_all.tar.gz"
    sha256 "8341f2daff692566a0ce20b11fe180a279a4693d70f2504e1f26e9b14d341a24"

    def install
      bin.install "publishgo"
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/archivebyarunavabasucom/publishgo/releases/download/0.0.3/publishgo_0.0.3_linux_amd64.tar.gz"
        sha256 "632f13a981e41863f841959bc013ff51651b2bc650cfcf7b9008fa6044118c16"

        def install
          bin.install "hellobrew"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/archivebyarunavabasucom/publishgo/releases/download/0.0.3/publishgo_0.0.3_linux_arm64.tar.gz"
        sha256 "c8a0b50f1144e0cff121f214ba324e409b8c3124bd596eb57d56ca01951d31f3"

        def install
          bin.install "hellobrew"
        end
      end
    end
  end
end
