# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Hellobrew < Formula
  desc ""
  homepage "https://github.com/archivebyarunavabasucom/homebrewtaps"
  version "0.0.6"

  on_macos do
    url "https://github.com/archivebyarunavabasucom/publishgo/releases/download/0.0.6/publishgo_0.0.6_darwin_all.tar.gz"
    sha256 "231743ee9977f9960a8a0143c64b9449cb1cdc344a9c264c1be7665059f3332b"

    def install
      bin.install "publishgo"
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/archivebyarunavabasucom/publishgo/releases/download/0.0.6/publishgo_0.0.6_linux_amd64.tar.gz"
        sha256 "9b96274ea5b664bb0cdff5368ed898dfbc5f5a029273be6e6d47a50682b88326"

        def install
          bin.install "hellobrew"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/archivebyarunavabasucom/publishgo/releases/download/0.0.6/publishgo_0.0.6_linux_arm64.tar.gz"
        sha256 "5a0dec446609a1ede229c2c7c5f186c7b00d40a032cce704a713460b91120c08"

        def install
          bin.install "hellobrew"
        end
      end
    end
  end
end
