# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Hellobrew < Formula
  desc ""
  homepage "https://github.com/archivebyarunavabasucom/homebrewtaps"
  version "0.0.5"

  on_macos do
    url "https://github.com/archivebyarunavabasucom/publishgo/releases/download/0.0.5/publishgo_0.0.5_darwin_all.tar.gz"
    sha256 "15fd0e77a2c047d81d237273d258877e20eeab9a0b5a613fc606e8b59de1e066"

    def install
      bin.install "publishgo"
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/archivebyarunavabasucom/publishgo/releases/download/0.0.5/publishgo_0.0.5_linux_amd64.tar.gz"
        sha256 "ccf70e457f475b9d872342bfab20d2803ffcad5941d1c3fc1d4096a41310b183"

        def install
          bin.install "hellobrew"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/archivebyarunavabasucom/publishgo/releases/download/0.0.5/publishgo_0.0.5_linux_arm64.tar.gz"
        sha256 "edd834a4150952762fdea954af3a1ed7d13074b5d7b8830203a4f9b089f897de"

        def install
          bin.install "hellobrew"
        end
      end
    end
  end
end
